### ISSUE TITLE
STEP FAILED in caso di file hpan già presente

### ISSUE THREAD

**Issue by NavaA-nexi** [pagopa/rtd-ms-transaction-filter#18]
Dai test effettuati risulta che in caso di file degli HPAN già scaricato il batch logga lo step come failed durante le esecuzioni successive e non procede con l'elaborazione dei file.
A nostro avviso lo step dovrebbe essere loggato come ok e l'elaborazione dovrebbe procedere.

Si allegano le immaggini dei log sulle tabelle Oracle

![batch_acquirer_log_BATCH_JOB_EXECUTION](https://user-images.githubusercontent.com/71773897/94988761-f41d4600-056f-11eb-825a-f09da05a49ad.jpg)
![batch_acquirer_log_BATCH_STEP_EXECUTION](https://user-images.githubusercontent.com/71773897/94988762-f54e7300-056f-11eb-801e-4b1b0aeaa0f6.jpg)

**Comment by NavaA-nexi** [comment]
Allego log completo e file configurazione come da richiesta 
[batchAcq.log.2020-10-02.103.zip](https://github.com/pagopa/rtd-ms-transaction-filter/files/5327922/batchAcq.log.2020-10-02.103.zip)

[file configurazione.zip](https://github.com/pagopa/rtd-ms-transaction-filter/files/5327925/file.configurazione.zip)

**Comment by alessio-cialini-sia** [comment]
Errore non replicato in test, provare a configurare come segue:

- batchConfiguration.TransactionFilterBatch.hpanListRecovery.filePattern: ${ACQ_BATCH_INPUT_FILE_PATTERN:*.csv}
- batchConfiguration.TransactionFilterBatch.hpanListRecovery.filename: ${ACQ_BATCH_HPAN_LIST_FILENAME:hpanList}${ACQ_BATCH_INPUT_FILE_PATTERN:.csv}

**Comment by NavaA-nexi** [comment]
Abbiamo testato la configurazione indicata ma il problema persiste (verificato sia su ambiente Nexi che su ambiente fornitore)

Di seguito il log:

2020-10-06 12:16:00.301 ERROR 11072 --- [task-scheduler-1] o.s.batch.core.step.AbstractStep         : Encountered an error executing step transaction-filter-salt-hpan-list-recovery-step in job transaction-filter-job
 
org.apache.commons.io.FileExistsException: Destination 'resources/hpans/20201006_hpanList.csv' already exists
        at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:3001) ~[commons-io-2.6.jar!/:2.6]
        at it.gov.pagopa.rtd.transaction_filter.batch.step.tasklet.HpanListRecoveryTasklet.execute(HpanListRecoveryTasklet.java:95) ~[rtd-ms-transaction-filter-api-batch-1.0.0-RC7.jar!/:1.0.0-RC7]
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:137) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:319) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:147) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50) [spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
        at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:140) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at it.gov.pagopa.rtd.transaction_filter.batch.TransactionFilterBatch.executeBatchJob(TransactionFilterBatch.java:140) [rtd-ms-transaction-filter-api-batch-1.0.0-RC7.jar!/:1.0.0-RC7]
        at it.gov.pagopa.rtd.transaction_filter.batch.TransactionFilterScheduler.launchJob(TransactionFilterScheduler.java:32) [rtd-ms-transaction-filter-api-batch-1.0.0-RC7.jar!/:1.0.0-RC7]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_161]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_161]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]

**Comment by alessio-cialini-sia** [comment]
Problema ancora non replicabile, gli ambienti utilizzati per il test quale OS hanno?

**Comment by NavaA-nexi** [comment]
Entrambi gli ambienti hanno il seguente OS:  Red Hat Enterprise Linux Server release 7.6 (Maipo)

**Comment by alessio-cialini-sia** [comment]
Risolto in https://github.com/pagopa/rtd-ms-transaction-filter/commit/b9e1f14f3f449a57d57aece94024df483145af2f
