### ISSUE TITLE
Error hpanList.csv already exists

### ISSUE THREAD

**Issue by s77937** [pagopa/rtd-ms-transaction-filter#262]
2022-10-11 09:09:21.749 ERROR 896888 --- [           main] o.s.batch.core.step.AbstractStep         : Encountered an error executing step transaction-filter-salt-hpan-list-recovery-step in job transaction-filter-job

org.apache.commons.io.FileExistsException: Destination 'resources/hpans/20221011_hpanList.csv' already exists
        at org.apache.commons.io.FileUtils.moveFile(FileUtils.java:2568) ~[commons-io-2.2.jar!/:2.2]
        at it.gov.pagopa.rtd.transaction_filter.batch.step.tasklet.HpanListRecoveryTasklet.execute(HpanListRecoveryTasklet.java:100) ~[rtd-ms-transaction-filter-api-batch-1.2.5.jar!/:1.2.5]
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407) ~[spring-batch-core-4.3.6.jar!/:4.3.6]
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331) ~[spring-batch-core-4.3.6.jar!/:4.3.6]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.22.jar!/:5.3.22]
        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273) ~[spring-batch-core-4.3.6.jar!/:4.3.6]
        at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82) ~[spring-batch-core-4.3.6.jar!/:4.3.6]
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375) ~[spring-batch-infrastructure-4.3.6.jar!/:4.3.6]
        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215) ~[spring-batch-infrastructure-4.3.6.jar!/:4.3.6]
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145) ~[spring-batch-infrastructure-4.3.6.jar!/:4.3.6]
        at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258) ~[spring-batch-core-4.3.6.jar!/:4.3.6]
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208) ~[spring-batch-core-4.3.6.jar!/:4.3.6]
        at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:152) ~[spring-batch-core-4.3.6.jar!/:4.3.6]
        at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68) ~[spring-batch-core-4.3.6.jar!/:4.3.6]
        at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68) ~[spring-batch-core-4.3.6.jar!/:4.3.6]
        at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169) ~[spring-batch-core-4.3.6.jar!/:4.3.6]
        at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144) ~[spring-batch-core-4.3.6.jar!/:4.3.6]
        at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:137) ~[spring-batch-core-4.3.6.jar!/:4.3.6]
        at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:320) ~[spring-batch-core-4.3.6.jar!/:4.3.6]
        at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:149) ~[spring-batch-core-4.3.6.jar!/:4.3.6]
        at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50) ~[spring-core-5.3.22.jar!/:5.3.22]
        at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:140) ~[spring-batch-core-4.3.6.jar!/:4.3.6]
        at it.gov.pagopa.rtd.transaction_filter.batch.TransactionFilterBatch.executeBatchJob(TransactionFilterBatch.java:163) ~[rtd-ms-transaction-filter-api-batch-1.2.5.jar!/:1.2.5]
        at it.gov.pagopa.rtd.transaction_filter.RtdTransactionFilterApplication.run(RtdTransactionFilterApplication.java:52) ~[classes!/:1.2.5]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-2.7.3.jar!/:2.7.3]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755) ~[spring-boot-2.7.3.jar!/:2.7.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.7.3.jar!/:2.7.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.3.jar!/:2.7.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.3.jar!/:2.7.3]
        at it.gov.pagopa.rtd.transaction_filter.RtdTransactionFilterApplication.main(RtdTransactionFilterApplication.java:39) ~[classes!/:1.2.5]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[rtd-ms-transaction-filter-1.2.5.jar:1.2.5]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[rtd-ms-transaction-filter-1.2.5.jar:1.2.5]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[rtd-ms-transaction-filter-1.2.5.jar:1.2.5]
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467) ~[rtd-ms-transaction-filter-1.2.5.jar:1.2.5]

**Comment by TommasoLencioni** [comment]
Assicuratevi di avere la variabile di ambiente `ACQ_BATCH_HPAN_ON_SUCCESS` impostata a `DELETE`.

**Comment by TommasoLencioni** [comment]
@s77937 possiamo chiudere la issue?

**Comment by s77937** [comment]
Sì grazie

Da: Tommaso Lencioni ***@***.***>
Inviato: mercoledì 19 ottobre 2022 11:23
A: pagopa/rtd-ms-transaction-filter ***@***.***>
Cc: s77937 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [pagopa/rtd-ms-transaction-filter] Error hpanList.csv already exists (Issue #262)


Caution! External email. Do not open attachments or click links, unless this email comes from a known sender and you know the content is safe.

@s77937<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fs77937&data=05%7C01%7Cmarco.maglione%40worldline.com%7C3d250a70afb049c0594a08dab1b3932d%7Cfda9decfe89243ac9d9f1a493f9f98d0%7C0%7C0%7C638017682071206144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PeByNcfvws3REhZcne4GOenkESmHy2Qhqf%2FBY1N3kp0%3D&reserved=0> possiamo chiudere la issue?

-
Reply to this email directly, view it on GitHub<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpagopa%2Frtd-ms-transaction-filter%2Fissues%2F262%23issuecomment-1283697545&data=05%7C01%7Cmarco.maglione%40worldline.com%7C3d250a70afb049c0594a08dab1b3932d%7Cfda9decfe89243ac9d9f1a493f9f98d0%7C0%7C0%7C638017682071206144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=n%2Fh0YuXglNE%2Bz0MQCxF%2FPB0Izuedoiyqk133G%2FwVp2s%3D&reserved=0>, or unsubscribe<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAR3RTBKNOLYIMWD2SRN7KYLWD64YTANCNFSM6AAAAAARCADXQI&data=05%7C01%7Cmarco.maglione%40worldline.com%7C3d250a70afb049c0594a08dab1b3932d%7Cfda9decfe89243ac9d9f1a493f9f98d0%7C0%7C0%7C638017682071206144%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ND617V0QdMrQUV2BZEKIAi%2FWbWFiO9GGaaunP4F2tzU%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

Worldline, Cardlink, GoPay and Santeos are registered trademarks and trade names owned by the Worldline Group. This e-mail and any documents attached are confidential and intended solely for the addressee. It may also be privileged. If you are not the intended recipient of this e-mail, you are not authorized to copy, disclose, use or retain it. Please notify the sender immediately and delete this e-mail (including any attachments) from your systems. As e-mails may be intercepted, amended or lost, they are not secure. Therefore, Worldline's and its subsidiaries' liability cannot be triggered for the message content. Although the Worldline Group endeavors to maintain a virus-free network, we do not warrant that this e-mail is virus-free and do not accept liability for any damages, losses or consequences resulting from any transmitted virus if any. The risks are deemed to be accepted by anyone who communicates with Worldline or its subsidiaries by e-mail.
