### ISSUE TITLE
Errore durante il download della lista dei pan

### ISSUE THREAD

**Issue by mripari** [pagopa/rtd-ms-transaction-filter#55]
Riceviamo il seguente errore:

"transaction-filter-salt-hpan-list-recovery-step"

Saluti,
Mauro

**Comment by alessio-cialini-sia** [comment]
Buonasera,

Quanto riportato è semplicemente lo step del recupero del salt, è possibile ci sia stata una breve interruzione del servizio, suggerirei di ripetere l'operazione. Al momento entrambi i servizi esposti (recupero salt e lista) sono contattabili con i ritorni attesi, da verifiche effettuate.

In ogni caso chiederei dove possibile di riportare una traccia di log più parlante, dato che con quanto riportato è impossibile dare indicazioni specifiche.

Grazie,

Alessio Cialini

**Comment by mripari** [comment]
Questo l'errore:
"feign.FeignException: Read timed out reading GET Libraesva ESG ha rilevato un possibile tentativo di phishing da "prod.cstar.pagopa.it:443" https://prod.cstar.pagopa.it:443/rtd/payment-instrument-manager/hashed-pans
at feign.FeignException.errorReading(FeignException.java:119)
at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:157)
at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:80)
at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
at com.sun.proxy.$Proxy94.getList(Unknown Source)
at it.gov.pagopa.rtd.transaction_filter.connector.HpanRestClientImpl.getList(HpanRestClientImpl.java:86)
at it.gov.pagopa.rtd.transaction_filter.service.HpanConnectorServiceImpl.getHpanList(HpanConnectorServiceImpl.java:23)
at it.gov.pagopa.rtd.transaction_filter.batch.step.tasklet.HpanListRecoveryTasklet.execute(HpanListRecoveryTasklet.java:100)
at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407)
at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273)
at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82)
at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375)
at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145)
at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258)
at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208)
at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68)
at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68)
at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169)
at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:137)
at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.jav"

**Comment by alessio-cialini-sia** [comment]
Buongiorno,

Giudicando dal messaggio "**Libraesva ESG ha rilevato un possibile tentativo di phishing da "prod.cstar.pagopa.it:443"**" direi che potrebbe esserci un blocco su qualche apparato intermedio, nel mentre la richiesta rimane pending per via del download di un file di dimensioni "elevate", poichè non è un messaggio standard all'interno dell'applicativo. In tal caso dovrà essere introdotta una regola che permetta alla richiesta di download di rimanere attiva per il tempo necessario al download, considerando la mole crescente di strumenti registrati.

Da test effettuati un run di prova del batch riesce a scaricare correttamente il file con le configurazioni di default, ma se volete potete aumentare i timeout applicativi tramite le seguenti proprietà  di configurazione:

feign.client.config.hpan-service.connectTimeout=${REST_CLIENT_CONNECT_TIMEOUT:${HPAN_REST_CLIENT_CONNECT_TIMEOUT:5000}}
feign.client.config.hpan-service.readTimeout=${REST_CLIENT_READ_TIMEOUT:${HPAN_REST_CLIENT_READ_TIMEOUT:5000}}

Saluti,

Alessio Cialini

**Comment by mripari** [comment]
Ciao,
il problema si è di nuovo verificato. Questa volta il messaggio è il seguente:

step message:
"feign.FeignException$NotFound: status 404 reading HpanRestConnector#getSalt(String)
at feign.FeignException.clientErrorStatus(FeignException.java:165)
at feign.FeignException.errorStatus(FeignException.java:141)
at feign.FeignException.errorStatus(FeignException.java:133)
at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92)
at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:151)
at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:80)
at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
at com.sun.proxy.$Proxy94.getSalt(Unknown Source)
at it.gov.pagopa.rtd.transaction_filter.connector.HpanRestClientImpl.getSalt(HpanRestClientImpl.java:175)
at it.gov.pagopa.rtd.transaction_filter.service.HpanConnectorServiceImpl.getSalt(HpanConnectorServiceImpl.java:28)
at it.gov.pagopa.rtd.transaction_filter.batch.step.tasklet.SaltRecoveryTasklet.execute(SaltRecoveryTasklet.java:35)
at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407)
at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331)
at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273)
at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82)
at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375)
at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145)
at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258)
at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208)
at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68)
at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68)
at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169)

**Comment by alessio-cialini-sia** [comment]
Buongiorno,

In questo caso si riporta un 404 sul metodo di recupero del salt. Da verifiche effettuate alle 14:36 non ci risulta che il servizio sia giù, consiglierei di riprovare con l'esecuzione.

Buon proseguimento,

Alessio Cialini
