### ISSUE TITLE
Impossibile scaricare salt

### ISSUE THREAD

**Issue by NavaA-nexi** [pagopa/rtd-ms-transaction-filter#58]
Buongiorno,

come segnalato via email e tramite apertura delle issue #55 #56 #57 da ieri stiamo avendo problemi con il funzionamento del batch acquirer.   Abbiamo provato a restartare il batch ma i problemi persistono.  Il batch ha a disposizione tutta la RAM della macchina che è stata configurata secondo le specifiche fornite nel documento RTD Acquirer Interface.

L'ultima esecuzione ha dato errore sullo step transaction-filter-salt-recovery-step

Questo il dettaglio dell'errore:

feign.FeignException$NotFound: status 404 reading HpanRestConnector#getSalt(String)
	at feign.FeignException.clientErrorStatus(FeignException.java:165)
	at feign.FeignException.errorStatus(FeignException.java:141)
	at feign.FeignException.errorStatus(FeignException.java:133)
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:151)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:80)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy94.getSalt(Unknown Source)
	at it.gov.pagopa.rtd.transaction_filter.connector.HpanRestClientImpl.getSalt(HpanRestClientImpl.java:175)
	at it.gov.pagopa.rtd.transaction_filter.service.HpanConnectorServiceImpl.getSalt(HpanConnectorServiceImpl.java:28)
	at it.gov.pagopa.rtd.transaction_filter.batch.step.tasklet.SaltRecoveryTasklet.execute(SaltRecoveryTasklet.java:35)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)

**Chiediamo di avere un contatto telefonico al fine di verificare insieme le problematiche.**  

Grazie

**Comment by DenisaBraho** [comment]
Ciao, la questione è stata indirizzata e risolta.
Grazie
