### ISSUE TITLE
Errore 403 durante l'invocazione dei servizi in ambiente SIT

### ISSUE THREAD

**Issue by vghetta** [pagopa/rtd-ms-transaction-filter#59]
abbiamo provato in ambiente SIT a richiamare il servizio 
https://bpd-dev.azure-api.net:443/rtd/payment-instrument-manager/hashed-pans

Il client è stato abilitato a TLS 1.2 come indicato dal documento RTD_Acquirer_Interface_V3.pdf tramite keystore.jks (generato a partire dal certificato template self signed opportunamente modificato) e truststore.jks.
Inoltre è stata inserita nel file di configurazione la primary subscription key ottenuta dalla registrazione al portare sviluppatori di Azure.
Il batch si avvia regolarmente ma al momento di invocare il servizio otteniamo questo errore :

2020-12-15 10:37:14.576 ERROR 9016 --- [           main] o.s.batch.core.step.AbstractStep         : Encountered an error executing step transaction-filter-salt-hpan-list-recovery-step in job transaction-filter-job
feign.FeignException$Forbidden: status 403 reading HpanRestConnector#getList(String)
        at feign.FeignException.clientErrorStatus(FeignException.java:163) ~[feign-core-10.4.0.jar!/:na]
        at feign.FeignException.errorStatus(FeignException.java:141) ~[feign-core-10.4.0.jar!/:na]
        at feign.FeignException.errorStatus(FeignException.java:133) ~[feign-core-10.4.0.jar!/:na]
        at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92) ~[feign-core-10.4.0.jar!/:na]
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:151) ~[feign-core-10.4.0.jar!/:na]
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:80) ~[feign-core-10.4.0.jar!/:na]
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103) ~[feign-core-10.4.0.jar!/:na]
        at com.sun.proxy.$Proxy90.getList(Unknown Source) ~[na:na]

Forse tale errore è dovuto alla necessità di registrare il nostro client presso i server di Azure tramite il nostro certificato.
Abbiamo il file .pfx contenente il certificato per Allitude s.p.a. (il nostro Acquirer) ma non sappiamo a chi dobbiamo inviarlo per farci abilitare.

**Comment by alessio-cialini-sia** [comment]
Buongiorno,

Per le richieste inerenti al caricamento dei certificati per SIT inviate i certificati da caricare all'indirizzo TeamCentroStella@sia.eu.

Saluti,

Alessio Cialini

**Comment by vghetta** [comment]
La ringrazio. Abbiamo inoltrato il certificato all'indirizzo mail suggerito

**Comment by vghetta** [comment]
In seguito a scambio mail con TeamCentroStella riporto qui i passaggi seguiti :

1. Abbiamo generato il certificato self-signed e la chiave privata tramite il comando :

openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout privateKey.key -out certificate.cer

2. Abbiamo inviato il cer a TeamCentroStella.

3. A partire dalla chiave privata e dal certificato generati al punto 1 abbiamo generato un pfx di appoggio con il comando :
 
openssl pkcs12 -export -out tmp.pfx -inkey privateKey.key -in certificate.cer
 
Per poi creare il keystore con il comando :
 
keytool -importkeystore -srckeystore tmp.pfx -srcstoretype pkcs12 -destkeystore keystore.jks -deststoretype JKS
 
Questo keystore è indicato nel file di configurazione application.yml nella sezione 
 
key-store:
      file: file:${HPAN_SERVICE_KEY_STORE_FILE:resources/keys/keystore.jks}
      type: ${HPAN_SERVICE_KEY_STORE_TYPE:#{null}}
      algorithm: ${HPAN_SERVICE_KEY_STORE_ALGORITHM:#{null}}
      password: ${HPAN_SERVICE_KEY_STORE_PASSWORD:allitude}
 
Il batch per test è installato su un pc e la struttura delle cartelle è la seguente :
 
<cartella di installazione batch>  -> in questa cartella è presente il jar e il file yml
<cartella di installazione batch>/resources/keys -> in questa cartella sono presenti i files keystore.jks e truststore.jks

Purtroppo al lancio del batch, al primo tentativo di chiamata della funzione hashed-pans, otteniamo sempre un errore 403

2020-12-21 10:48:23.756 ERROR 17468 --- [           main] o.s.batch.core.step.AbstractStep         : Encountered an error executing step transaction-filter-salt-hpan-list-recovery-step in job transaction-filter-job

feign.FeignException$Forbidden: status 403 reading HpanRestConnector#getList(String)
        at feign.FeignException.clientErrorStatus(FeignException.java:163) ~[feign-core-10.4.0.jar!/:na]
        at feign.FeignException.errorStatus(FeignException.java:141) ~[feign-core-10.4.0.jar!/:na]
        at feign.FeignException.errorStatus(FeignException.java:133) ~[feign-core-10.4.0.jar!/:na]
        at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92) ~[feign-core-10.4.0.jar!/:na]
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:151) ~[feign-core-10.4.0.jar!/:na]
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:80) ~[feign-core-10.4.0.jar!/:na]
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103) ~[feign-core-10.4.0.jar!/:na]
        at com.sun.proxy.$Proxy90.getList(Unknown Source) ~[na:na]
        at it.gov.pagopa.rtd.transaction_filter.connector.HpanRestClientImpl.getList(HpanRestClientImpl.java:86) ~[rtd-ms-transaction_filter-integration-rest-1.0.0-RC9.jar!/:1.0.0-RC9]
        at it.gov.pagopa.rtd.transaction_filter.service.HpanConnectorServiceImpl.getHpanList(HpanConnectorServiceImpl.java:23) ~[rtd-ms-transaction-filter-core-1.0.0-RC9.jar!/:1.0.0-RC9]
        at it.gov.pagopa.rtd.transaction_filter.batch.step.tasklet.HpanListRecoveryTasklet.execute(HpanListRecoveryTasklet.java:100) ~[rtd-ms-transaction-filter-api-batch-1.0.0-RC9.jar!/:1.0.0-RC9]
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
        at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:137) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:319) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:147) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50) [spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
        at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:140) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
        at it.gov.pagopa.rtd.transaction_filter.batch.TransactionFilterBatch.executeBatchJob(TransactionFilterBatch.java:152) [rtd-ms-transaction-filter-api-batch-1.0.0-RC9.jar!/:1.0.0-RC9]
        at it.gov.pagopa.rtd.transaction_filter.RtdTransactionFilterApplication.run(RtdTransactionFilterApplication.java:52) [classes!/:1.0.0-RC9]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) [spring-boot-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768) [spring-boot-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
        at it.gov.pagopa.rtd.transaction_filter.RtdTransactionFilterApplication.main(RtdTransactionFilterApplication.java:39) [classes!/:1.0.0-RC9]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_45]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_45]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_45]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [bpd-ms-rtd-ms-transaction-filter-1.0.0-RC9-FATJAR.jar:1.0.0-RC9]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [bpd-ms-rtd-ms-transaction-filter-1.0.0-RC9-FATJAR.jar:1.0.0-RC9]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [bpd-ms-rtd-ms-transaction-filter-1.0.0-RC9-FATJAR.jar:1.0.0-RC9]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [bpd-ms-rtd-ms-transaction-filter-1.0.0-RC9-FATJAR.jar:1.0.0-RC9]

**Comment by alessio-cialini-sia** [comment]
Buongiorno,

In relazione a quanto indicato, sarebbe anche da indicare se il sistema presenta un proxy nel mezzo della comunicazione, ed il contenuto del jks usato come truststore.

Grazie,

Buon proseguimento,

Alessio Cialini

**Comment by vghetta** [comment]
Ho verificato con i sistemisti i quali mi dicono che :

- non esiste un proxy
- esiste un firewall aziendale di navigazione ma che sembra non bloccare le chiamate

Per quanto riguarda il truststore contiene due chiavi :

λ keytool -list -keystore truststore.jks
Immettere la password del keystore:

Tipo keystore: JKS
Provider keystore: SUN

Il keystore contiene 2 voci

mykey, 14-dic-2020, trustedCertEntry,
Impronta digitale certificato (SHA1): DF:3C:24:F9:BF:D6:66:76:1B:26:80:73:FE:06:D1:CC:8D:4F:82:A4
cstar-server, 14-dic-2020, trustedCertEntry,
Impronta digitale certificato (SHA1): B3:1E:B1:B7:40:E3:6C:84:02:DA:DC:37:D4:4D:F5:D4:67:49:52:F9

Il truststore è stato creato con i comandi :

keytool -import -trustcacerts -file entrust_l1k_chain_root.cer -alias cstar-server -keystore truststore2.jks -storepass allitude
keytool -import -trustcacerts -file DigiCertGlobalRootG2.crt -keystore truststore2.jks -storepass allitude

**Comment by mdesogus** [comment]
Buongiorno,

come da accordi verbali condivisi nella call di ieri (21/12/2020) restiamo in attesa di aggiornamenti.

grazie

**Comment by vghetta** [comment]
Ripropongo in dettaglio quanto eseguito finora in ambiente SIT 

Ambiente utilizzato per i test

Il batch al momento viene testato su di un pc con Windows 10 collegato alla network aziendale tramite VPN.
Il jar del batch è in una cartella e nella stessa cartella è presente il file application.yml con le nostre configurazioni.
I file dei certificati (keystore e truststore) sono in una sottcartella resources/keys

|cartella di installazione batch| -> in questa cartella è presente il jar e il file yml
|cartella di installazione batch|/resources/keys -> in questa cartella sono presenti i files keystore2.jks e cacerts.jks

Non ci sono proxy mentre è presente un firewall aziendale di navigazione. I sistemisti hanno verificato e non dovrebbero esserci problemi legati a quest’ultimo (abbiamo controllato i log durante l’esecuzione del batch e non vi sono drop)

Registrazioni al portale Azure

Mi sono registrato al portale sviluppatori del Centro Stella e ho richiesto una sottoscrizione per il prodotto rtd-api-product ottenendo una primary key e una secondary key. La primary key è stata riportata nel file application.yml nella property rest-client.hpan.api.key.
La mail con cui mi sono registrato è valerio.ghetta@allitude.it.

Generazione dei certificati 

Per la generazione dei certificati abbiamo seguito i seguenti passaggi da voi suggeriti.

-	Abbiamo generato una chiave privata e un certificato self-signed con il comando :

openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout privateKey.key -out certificate.cer

valorizzando i campi con i seguenti dati 

Generating a 2048 bit RSA private key
.........+++++
...................................................................................................+++++
writing new private key to 'ciccio.key'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:IT
State or Province Name (full name) [Some-State]:Trento
Locality Name (eg, city) []:Trento
Organization Name (eg, company) [Internet Widgits Pty Ltd]:Allitude spa
Organizational Unit Name (eg, section) []:
Common Name (e.g. server FQDN or YOUR name) []:
Email Address []:


                Abbiamo chiesto ai sistemisti riguardo la CA del certificato e la risposta è stata quella anticipata ieri : il certificato fa lui stesso da CA, in quanto è nella natura stessa di un certificato self-signed.

-	A partire dalla chiave privata e dal certificato generati al passaggio precedente abbiamo generato un pfx di appoggio con il comando :

openssl pkcs12 -export -out tmp.pfx -inkey privateKey.key -in certificate.cer

-	Dal tmp.pfx abbiamo poi generato un keystore con il comando : 

keytool -importkeystore -srckeystore tmp.pfx -srcstoretype pkcs12 -destkeystore keystore2.jks -deststoretype JKS

                Per comodità e per evitare errori, le password del pfx e del jks sono le stesse. Questo keystore e questa password sono riportati nella
                Seguente configurazione del file application.yml

key-store:
file: file:${HPAN_SERVICE_KEY_STORE_FILE:resources/keys/keystore.jks}
type: ${HPAN_SERVICE_KEY_STORE_TYPE:#{null}}
algorithm: ${HPAN_SERVICE_KEY_STORE_ALGORITHM:#{null}}
password: ${HPAN_SERVICE_KEY_STORE_PASSWORD:allitude}

-	Dopo la call di ieri abbiamo cambiato il truststore. 
Abbiamo preso il cacerts presente nella jdk1.8.0_60 installata sul mio pc e lo abbiamo utilizzato come truststore as-is.
Abbiamo però ricevuto un errore di SSL Handshake Errors come segnalato nella FAQ presenti su GitHub.
Abbiamo seguito le indicazioni per la soluzione del problema e abbiamo integrato il cacerts.jks con il certificato DigiCert Global Root G2 CA.

keytool -import -trustcacerts -file DigiCertGlobalRootG2.crt -keystore cacerts.jks -storepass changeit

-	A questo punto il batch parte, riconosce la presenza di un file con le transazioni e cerca di collegarsi al servizio hashed-pans ma ottiene sempre lo stesso errore 403

2020-12-21 10:48:23.756 ERROR 17468 --- [ main] o.s.batch.core.step.AbstractStep : Encountered an error executing step transaction-filter-salt-hpan-list-recovery-step in job transaction-filter-job

feign.FeignException$Forbidden: status 403 reading HpanRestConnector#getList(String)

Per completezza, aggiungo che nel log del batch, prima dell’eccezione viene chiaramente segnalato che il certificato non è verificato e viene riportata una fingerprint. 
La stessa fingerprint la ritroviamo sia nel certificato inviato a CentroStella sia nel certificato contenuto nel keystore referenziato dal file application.yml

**Comment by mdesogus** [comment]
buongiorno,

abbiamo sostituito il certificato caricato precedentemente con quello fornitoci via mail.
potreste riprovare e fornirci riscontro? 

grazie

**Comment by vghetta** [comment]
Ora il collegamento sembra funzionare. Il batch ha scaricato un file di circa 66 Mb contenente poco piu di un milione di hash pans.
Ora abbiamo un errore di socket timeout durante la chiamata per la richiesta del salt, ma per quanto riguarda l'errore 403 sembra risolto.

**Comment by mdesogus** [comment]
Per il timeout occorre verificare se gli apparati intermedi consentono di restare "in attesa" per l'intervallo temporale necessario, eventualmente si potrebbero anche aumentare i parametri di timeout previsti in configurazione.
