### ISSUE TITLE
Handshake_failure

### ISSUE THREAD

**Issue by s77937** [pagopa/rtd-ms-transaction-filter#63]
Ciao,
sono riuscito a fare mutua autenticazione in ambiente windows con i WS dell'ambiente di UAT.
Ma in ambiente Linux, dopo aver acquisito il certificato cliente sul keystore ed utilizzando lo stesso truststore usando su windows, ho l'errore Handshake_failure.

eign.RetryableException: Received fatal alert: handshake_failure executing GET https://test.cstar.pagopa.it:443/rtd/payment-instrument-manager/hashed-pans
	at feign.FeignException.errorExecuting(FeignException.java:213) ~[feign-core-10.4.0.jar!/:na]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:115) ~[feign-core-10.4.0.jar!/:na]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:80) ~[feign-core-10.4.0.jar!/:na]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103) ~[feign-core-10.4.0.jar!/:na]
	at com.sun.proxy.$Proxy90.getList(Unknown Source) ~[na:1.8.0]
	at it.gov.pagopa.rtd.transaction_filter.connector.HpanRestClientImpl.getList(HpanRestClientImpl.java:86) ~[rtd-ms-transaction_filter-integration-rest-1.0.0-RC9.jar!/:1.0.0-RC9]
	at it.gov.pagopa.rtd.transaction_filter.service.HpanConnectorServiceImpl.getHpanList(HpanConnectorServiceImpl.java:23) ~[rtd-ms-transaction-filter-core-1.0.0-RC9.jar!/:1.0.0-RC9]
	at it.gov.pagopa.rtd.transaction_filter.batch.step.tasklet.HpanListRecoveryTasklet.execute(HpanListRecoveryTasklet.java:100) ~[rtd-ms-transaction-filter-api-batch-1.0.0-RC9.jar!/:1.0.0-RC9]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:137) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:319) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:147) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50) [spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:140) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at it.gov.pagopa.rtd.transaction_filter.batch.TransactionFilterBatch.executeBatchJob(TransactionFilterBatch.java:152) [rtd-ms-transaction-filter-api-batch-1.0.0-RC9.jar!/:1.0.0-RC9]
	at it.gov.pagopa.rtd.transaction_filter.RtdTransactionFilterApplication.run(RtdTransactionFilterApplication.java:52) [classes!/:1.0.0-RC9]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) [spring-boot-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768) [spring-boot-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
	at it.gov.pagopa.rtd.transaction_filter.RtdTransactionFilterApplication.main(RtdTransactionFilterApplication.java:39) [classes!/:1.0.0-RC9]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95) ~[na:1.8.0]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[na:1.8.0]
	at java.lang.reflect.Method.invoke(Method.java:508) ~[na:2.6 (12-09-2016)]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [bpd-ms-rtd-ms-transaction-filter-1.0.0-RC9-FATJAR.jar:1.0.0-RC9]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [bpd-ms-rtd-ms-transaction-filter-1.0.0-RC9-FATJAR.jar:1.0.0-RC9]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [bpd-ms-rtd-ms-transaction-filter-1.0.0-RC9-FATJAR.jar:1.0.0-RC9]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [bpd-ms-rtd-ms-transaction-filter-1.0.0-RC9-FATJAR.jar:1.0.0-RC9]
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at com.ibm.jsse2.j.a(j.java:12) ~[na:8.0 build_20160616]
	at com.ibm.jsse2.j.a(j.java:31) ~[na:8.0 build_20160616]
	at com.ibm.jsse2.as.b(as.java:806) ~[na:8.0 build_20160616]
	at com.ibm.jsse2.as.a(as.java:102) ~[na:8.0 build_20160616]
	at com.ibm.jsse2.as.i(as.java:969) ~[na:8.0 build_20160616]
	at com.ibm.jsse2.as.a(as.java:680) ~[na:8.0 build_20160616]
	at com.ibm.jsse2.as.startHandshake(as.java:859) ~[na:8.0 build_20160616]
	at com.ibm.net.ssl.www2.protocol.https.c.afterConnect(c.java:16) ~[na:8.0 build_20160616]
	at com.ibm.net.ssl.www2.protocol.https.d.connect(d.java:44) ~[na:8.0 build_20160616]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1561) ~[na:1.8.0]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1489) ~[na:1.8.0]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:491) ~[na:1.8.0]
	at com.ibm.net.ssl.www2.protocol.https.b.getResponseCode(b.java:1) ~[na:8.0 build_20160616]
	at feign.Client$Default.convertResponse(Client.java:82) ~[feign-core-10.4.0.jar!/:na]
	at feign.Client$Default.execute(Client.java:78) ~[feign-core-10.4.0.jar!/:na]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:110) ~[feign-core-10.4.0.jar!/:na]
	... 42 common frames omitted

Cosa sto sbagliando?

Grazie

**Comment by s77937** [comment]
Di seguito il keystore:
keytool -list -keystore uat-keystore.jks

Keystore type: jks
Keystore provider: IBMJCE

Your keystore contains 1 entry

36027, Dec 18, 2020, keyEntry,
Certificate fingerprint (SHA1): 53:EE:3F:53:DE:8C:C2:63:A7:B7:D4:58:42:D1:53:20:57:A7:8F:FF

E di seguito il cacerts:
Keystore type: jks
Keystore provider: IBMJCE

Your keystore contains 7 entries

bc2025ca, Nov 23, 2020, trustedCertEntry,
Certificate fingerprint (SHA1): D4:DE:20:D0:5E:66:FC:53:FE:1A:50:88:2C:78:DB:28:52:CA:E4:74
digicertglobalrootg2, Nov 23, 2020, trustedCertEntry,
Certificate fingerprint (SHA1): DF:3C:24:F9:BF:D6:66:76:1B:26:80:73:FE:06:D1:CC:8D:4F:82:A4
36027, Dec 17, 2020, trustedCertEntry,
Certificate fingerprint (SHA1): 53:EE:3F:53:DE:8C:C2:63:A7:B7:D4:58:42:D1:53:20:57:A7:8F:FF
cicsca, Nov 15, 2010, trustedCertEntry,
Certificate fingerprint (SHA1): BA:6C:43:A8:54:05:F0:99:8F:22:C8:8B:22:89:C3:E1:4F:95:5B:35
endeca-ca, Dec 17, 2020, trustedCertEntry,
Certificate fingerprint (SHA1): 84:B5:B6:5B:D1:9F:1E:40:94:6F:27:B6:06:88:39:4F:32:FA:D9:28
pagopa, Dec 17, 2020, trustedCertEntry,
Certificate fingerprint (SHA1): 84:B5:B6:5B:D1:9F:1E:40:94:6F:27:B6:06:88:39:4F:32:FA:D9:28
cstar-server, Nov 23, 2020, trustedCertEntry,
Certificate fingerprint (SHA1): 9E:1A:0C:35:E7:14:B6:97:92:D0:90:B2:CC:4B:BA:45:83:3C:30:15

**Comment by alessio-cialini-sia** [comment]
Buongiorno,

Assicuratevi che la connettività della macchina, o di eventuali apparati intermedi, permetta di poter effettuare correttamente l'handshake SSL (ad esempio il proxy).

Assicuratevi comunque che la configurazione sia effettivamente una replica esatta di quella utilizzata in precedenti esempi di esecuzione.

Inoltre vedo che state utilizzando una versione della jdk IBM, assicuratevi che il test precedente sia stato effettuato sulla stessa versione, perchè lo sviluppo del batch è stato eseguito su distribuzione Oracle, versione 1.8.

**Comment by s77937** [comment]
Risolto utilizzando la openJDK
