### ISSUE TITLE
Connection timeout su scrittura file di output su SFTP

### ISSUE THREAD

**Issue by s77937** [pagopa/rtd-ms-transaction-filter#64]
Buongiorno,
ricevo un errore di connection timeout nel tentativo di scrittura del file di output su SFTP server di UAT, probabilmente perché mi trovo dietro un proxy, ma non ho capito quali sono i parametri di configurazione del proxy anche per le chiamate SFTP.
Da altro ambiente, in cui non vi è necessità di configurare nessun proxy, sono riuscito a scrivere correttamente il file sul server SFTP di UAT.

2020-12-22 08:29:08.309  INFO 1945289 --- [rTaskExecutor-3] com.jcraft.jsch                          : Connecting to 193.203.229.79 port 10022
2020-12-22 08:31:18.909 ERROR 1945289 --- [rTaskExecutor-3] o.s.batch.core.step.AbstractStep         : Encountered an error executing step transaction-filter-send-step in job transaction-filter-job

org.springframework.integration.util.PoolItemNotAvailableException: Failed to obtain pooled item
	at org.springframework.integration.util.SimplePool.getItem(SimplePool.java:181) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.file.remote.session.CachingSessionFactory.getSession(CachingSessionFactory.java:132) ~[spring-integration-file-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.file.remote.RemoteFileTemplate.execute(RemoteFileTemplate.java:432) ~[spring-integration-file-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.file.remote.RemoteFileTemplate.send(RemoteFileTemplate.java:298) ~[spring-integration-file-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.file.remote.RemoteFileTemplate.send(RemoteFileTemplate.java:286) ~[spring-integration-file-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.file.remote.RemoteFileTemplate.send(RemoteFileTemplate.java:278) ~[spring-integration-file-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.file.remote.handler.FileTransferringMessageHandler.handleMessageInternal(FileTransferringMessageHandler.java:205) ~[spring-integration-file-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:170) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.handler.ReplyProducingMessageHandlerWrapper.handleRequestMessage(ReplyProducingMessageHandlerWrapper.java:49) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:127) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:170) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:403) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:151) ~[spring-messaging-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:143) ~[spring-messaging-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.gateway.MessagingGatewaySupport.send(MessagingGatewaySupport.java:429) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.sendOrSendAndReceive(GatewayProxyFactoryBean.java:628) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.invokeGatewayMethod(GatewayProxyFactoryBean.java:549) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.doInvoke(GatewayProxyFactoryBean.java:524) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.gateway.GatewayProxyFactoryBean.invoke(GatewayProxyFactoryBean.java:513) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at com.sun.proxy.$Proxy93.sendToSftp(Unknown Source) ~[na:na]
	at it.gov.pagopa.rtd.transaction_filter.connector.TransactionSftpConnector.sendFile(TransactionSftpConnector.java:17) ~[rtd-ms-transaction_filter-integration-sftp-1.0.0-RC9.jar!/:1.0.0-RC9]
	at it.gov.pagopa.rtd.transaction_filter.service.SftpConnectorServiceImpl.transferFile(SftpConnectorServiceImpl.java:22) ~[rtd-ms-transaction-filter-core-1.0.0-RC9.jar!/:1.0.0-RC9]
	at it.gov.pagopa.rtd.transaction_filter.batch.step.tasklet.TransactionSenderTasklet.execute(TransactionSenderTasklet.java:31) ~[rtd-ms-transaction-filter-api-batch-1.0.0-RC9.jar!/:1.0.0-RC9]
	at it.gov.pagopa.rtd.transaction_filter.batch.step.tasklet.TransactionSenderTasklet$$FastClassBySpringCGLIB$$1a3dbe1.invoke(<generated>) ~[rtd-ms-transaction-filter-api-batch-1.0.0-RC9.jar!/:1.0.0-RC9]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:136) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at it.gov.pagopa.rtd.transaction_filter.batch.step.tasklet.TransactionSenderTasklet$$EnhancerBySpringCGLIB$$ce6df3bd.execute(<generated>) ~[rtd-ms-transaction-filter-api-batch-1.0.0-RC9.jar!/:1.0.0-RC9]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:138) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:135) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_252]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_252]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_252]
Caused by: java.lang.IllegalStateException: failed to create SFTP Session
	at org.springframework.integration.sftp.session.DefaultSftpSessionFactory.getSession(DefaultSftpSessionFactory.java:391) ~[spring-integration-sftp-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.sftp.session.DefaultSftpSessionFactory.getSession(DefaultSftpSessionFactory.java:60) ~[spring-integration-sftp-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.file.remote.session.CachingSessionFactory$1.createForPool(CachingSessionFactory.java:83) ~[spring-integration-file-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.file.remote.session.CachingSessionFactory$1.createForPool(CachingSessionFactory.java:80) ~[spring-integration-file-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.util.SimplePool.doGetItem(SimplePool.java:191) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.util.SimplePool.getItem(SimplePool.java:172) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	... 60 common frames omitted
Caused by: java.lang.IllegalStateException: failed to connect
	at org.springframework.integration.sftp.session.SftpSession.connect(SftpSession.java:301) ~[spring-integration-sftp-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.integration.sftp.session.DefaultSftpSessionFactory.getSession(DefaultSftpSessionFactory.java:385) ~[spring-integration-sftp-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	... 65 common frames omitted
Caused by: com.jcraft.jsch.JSchException: java.net.ConnectException: Connection timed out (Connection timed out)
	at com.jcraft.jsch.Util.createSocket(Util.java:349) ~[jsch-0.1.54.jar!/:na]
	at com.jcraft.jsch.Session.connect(Session.java:215) ~[jsch-0.1.54.jar!/:na]
	at com.jcraft.jsch.Session.connect(Session.java:183) ~[jsch-0.1.54.jar!/:na]
	at org.springframework.integration.sftp.session.SftpSession.connect(SftpSession.java:292) ~[spring-integration-sftp-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	... 66 common frames omitted
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_252]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_252]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_252]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_252]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_252]
	at java.net.Socket.connect(Socket.java:607) ~[na:1.8.0_252]
	at java.net.Socket.connect(Socket.java:556) ~[na:1.8.0_252]
	at java.net.Socket.<init>(Socket.java:452) ~[na:1.8.0_252]
	at java.net.Socket.<init>(Socket.java:229) ~[na:1.8.0_252]
	at com.jcraft.jsch.Util.createSocket(Util.java:343) ~[jsch-0.1.54.jar!/:na]
	... 69 common frames omitted

**Comment by alessio-cialini-sia** [comment]
Nella versione attuale dell'integrazione SFTP su batch non è presente una configurazione del client che supporti il passaggio tramite proxy.

**Comment by alessio-cialini-sia** [comment]
Per verifica, potete provare la configurazione introdotta in commit https://github.com/pagopa/rtd-ms-transaction-filter/commit/226bea219c3e878c0f59eb12958ba662ae3d4de6.

Il branch è di sviluppo, potete verificare le proprietà inserite direttamente dal changelog.

**Comment by s77937** [comment]
Ho provato con la configurazione introdotta in commit 226bea2, ma non sono riuscito ancora a collegarmi.
Verifico con i nostri sistemisti, magari non è aperta la porta per l'sftp da questa macchina.

**Comment by alessio-cialini-sia** [comment]
Per utilizzare la configurazione riportata assicuratevi di generare un installazione da sorgente, estratta dal branch development.
