### ISSUE TITLE
Di nuovo java.lang.Exception: Recovered PAN list exceeding a day in ambiente SIT

### ISSUE THREAD

**Issue by vghetta** [pagopa/rtd-ms-transaction-filter#73]
Buongiorno,
da stamattina non riusciamo più a scaricare la lista dei pan in ambiente SIT.
I tentativi sono stati fatti sia da macchina windows che su macchina AIX.
L'errore è il seguente

2021-01-18 10:50:15.450 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] ---> GET https://bpd-dev.azure-api.net/rtd/payment-instrument-manager/hashed-pans HTTP/1.1
2021-01-18 10:50:15.451 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] Ocp-Apim-Subscription-Key: b54116814a2b4dc7b5397d199338b5c2
2021-01-18 10:50:15.452 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] ---> END HTTP (0-byte body)
2021-01-18 10:50:17.629 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] <--- HTTP/1.1 200 OK (2176ms)
2021-01-18 10:50:17.630 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] accept-ranges: bytes
2021-01-18 10:50:17.630 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] content-length: 344988549
2021-01-18 10:50:17.631 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] content-md5: oOiLfTQcPBImOJg3pWms7g==
2021-01-18 10:50:17.631 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] content-type: application/octet-stream
2021-01-18 10:50:17.631 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] date: Mon, 18 Jan 2021 09:50:17 GMT
2021-01-18 10:50:17.632 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] etag: "0x8D8BACCA0F315D5"
2021-01-18 10:50:17.632 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] last-modified: Sun, 17 Jan 2021 09:45:30 GMT
2021-01-18 10:50:17.632 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] x-ms-blob-type: BlockBlob
2021-01-18 10:50:17.633 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] x-ms-creation-time: Mon, 22 Jun 2020 15:58:35 GMT
2021-01-18 10:50:17.633 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] x-ms-lease-state: available
2021-01-18 10:50:17.633 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] x-ms-lease-status: unlocked
2021-01-18 10:50:17.634 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] x-ms-meta-sha256: e5daaacbfb85e366b80df43687db9de1404128724604293ddc0319984b9baf3c
2021-01-18 10:50:17.634 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] x-ms-request-id: 6af38d48-401e-0012-677f-edd33f000000
2021-01-18 10:50:17.634 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] x-ms-server-encrypted: true
2021-01-18 10:50:17.635 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] x-ms-version: 2019-02-02
2021-01-18 10:50:17.635 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] 
2021-01-18 10:52:17.615 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] Binary data
2021-01-18 10:52:17.616 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] <--- END HTTP (344988549-byte body)
2021-01-18 10:52:18.234 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestClientImpl   : currentDate is: 18-1-2021 10:52:18 AM
2021-01-18 10:52:18.235 DEBUG 26608000 --- [main] i.g.p.r.t.connector.HpanRestClientImpl   : fileCreationTime is 17-1-2021 09:45:30 AM
2021-01-18 10:52:18.265 ERROR 26608000 --- [main] o.s.batch.core.step.AbstractStep         : Encountered an error executing step transaction-filter-salt-hpan-list-recovery-step in job transaction-filter-job

java.lang.Exception: Recovered PAN list exceeding a day
	at it.gov.pagopa.rtd.transaction_filter.connector.HpanRestClientImpl.getList(HpanRestClientImpl.java:111) ~[rtd-ms-transaction_filter-integration-rest-1.0.0-RC9.jar!/:1.0.0-RC9]
	at it.gov.pagopa.rtd.transaction_filter.service.HpanConnectorServiceImpl.getHpanList(HpanConnectorServiceImpl.java:23) ~[rtd-ms-transaction-filter-core-1.0.0-RC9.jar!/:1.0.0-RC9]
	at it.gov.pagopa.rtd.transaction_filter.batch.step.tasklet.HpanListRecoveryTasklet.execute(HpanListRecoveryTasklet.java:100) ~[rtd-ms-transaction-filter-api-batch-1.0.0-RC9.jar!/:1.0.0-RC9]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:137) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:319) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:147) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50) [spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:140) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
	at it.gov.pagopa.rtd.transaction_filter.batch.TransactionFilterBatch.executeBatchJob(TransactionFilterBatch.java:152) [rtd-ms-transaction-filter-api-batch-1.0.0-RC9.jar!/:1.0.0-RC9]
	at it.gov.pagopa.rtd.transaction_filter.RtdTransactionFilterApplication.run(RtdTransactionFilterApplication.java:52) [classes!/:1.0.0-RC9]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784) [spring-boot-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768) [spring-boot-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) [spring-boot-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.8.RELEASE.jar!/:2.2.8.RELEASE]
	at it.gov.pagopa.rtd.transaction_filter.RtdTransactionFilterApplication.main(RtdTransactionFilterApplication.java:39) [classes!/:1.0.0-RC9]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90) ~[na:1.8.0]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55) ~[na:1.8.0]
	at java.lang.reflect.Method.invoke(Method.java:508) ~[na:1.8.0]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [gtpos-batch-cashback-di-stato.jar:1.0.0-RC9]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [gtpos-batch-cashback-di-stato.jar:1.0.0-RC9]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [gtpos-batch-cashback-di-stato.jar:1.0.0-RC9]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [gtpos-batch-cashback-di-stato.jar:1.0.0-RC9]

Abbiamo visto che era già stata aperta una issue in merito (#51) e che risulterebbe anche chiusa, ma stamattina l'errore continua a presentarsi e vorremmo sapere se si tratta di un problema momentaneo nell'erogazione del servizio hpans oppure se si  tratta di qualcosa che deve essere patchato.

saluti
Valerio

**Comment by vghetta** [comment]
Aggiornamento della problematica segnalata ieri con questa issue.
Oggi tutto sembra funzionare bene. La lista degli hpan viene scaricata in ambiente SIT con il batch eseguito sia su macchina Windows, sia su macchina AIX.
Vi chiederei quindi un commento sul perchè l'errore si presenta in questo modo arbitrario.
Si è trattato di un problema momentaneo del server nel rispondere alla richiesta della lista hpans?
Possiamo considerare come non significativi questi errori in ottica di un passaggio in ambienti UAT e produzione?

**Comment by alessio-cialini-sia** [comment]
Il problema si presenta quando non è stato generato il file giornaliero, lato batch è implementato un controllo per bloccare l'esecuzione nel caso si stia recuperando un file non aggiornato.

La generazione in SIT dovrebbe essere ora regolare, potete tranquillamente proseguire.
