### ISSUE TITLE
Impossibile scaricare il file salt-hpan

### ISSUE THREAD

**Issue by saracarissoni** [pagopa/rtd-ms-transaction-filter#74]
Si richiede di verificare il motivo per cui il Batch Acquirer non riesce a scaricare il file, l'errore che ottiene è il seguente:
"Encountered an error executing step transaction-filter-salt-hpan-list-recovery-step in job transaction-filter-job".
Grazie

**Comment by saracarissoni** [comment]
Potete cortesemente darci un riscontro?

**Comment by saracarissoni** [comment]
Questo l'errore riscontrato:
java.lang.Exception: Recovered PAN list exceeding a day
	at it.gov.pagopa.rtd.transaction_filter.connector.HpanRestClientImpl.getList(HpanRestClientImpl.java:111)
	at it.gov.pagopa.rtd.transaction_filter.service.HpanConnectorServiceImpl.getHpanList(HpanConnectorServiceImpl.java:23)
	at it.gov.pagopa.rtd.transaction_filter.batch.step.tasklet.HpanListRecoveryTasklet.execute(HpanListRecoveryTasklet.java:100)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:137)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:319)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:147)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:140)
	at it.gov.pagopa.rtd.transaction_filter.batch.TransactionFilterBatch.executeBatchJob(TransactionFilterBatch.java:152)
	at it.gov.pag

**Comment by alessio-cialini-sia** [comment]
Il file è stato rigenerato, potete procedere con l'esecuzione.
