### ISSUE TITLE
Impossibile scaricare il file salt-hpan

### ISSUE THREAD

**Issue by saracarissoni** [pagopa/rtd-ms-transaction-filter#79]
Si richiede di verificare il motivo per cui il Batch Acquirer non riesce a scaricare il file, l'errore che ottiene è il seguente:
"Encountered an error executing step transaction-filter-salt-hpan-list-recovery-step in job transaction-filter-job".
Grazie

Di seguito l'errore riscontrato:

feign.FeignException: Read timed out reading GET https://prod.cstar.pagopa.it:443/rtd/payment-instrument-manager/hashed-pans
	at feign.FeignException.errorReading(FeignException.java:119)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:157)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:80)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at com.sun.proxy.$Proxy94.getList(Unknown Source)
	at it.gov.pagopa.rtd.transaction_filter.connector.HpanRestClientImpl.getList(HpanRestClientImpl.java:86)
	at it.gov.pagopa.rtd.transaction_filter.service.HpanConnectorServiceImpl.getHpanList(HpanConnectorServiceImpl.java:23)
	at it.gov.pagopa.rtd.transaction_filter.batch.step.tasklet.HpanListRecoveryTasklet.execute(HpanListRecoveryTasklet.java:100)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:137)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.jav

**Comment by saracarissoni** [comment]
Ci sono aggiornamenti ? grazie

**Comment by alessio-cialini-sia** [comment]
Buongiorno, in caso di timeout fare riferimento alla proprietà di configurazione relativa del client feign, definita come segue:

feign:
  client:
    config:
      hpan-service:
        connectTimeout: ${REST_CLIENT_CONNECT_TIMEOUT:${HPAN_REST_CLIENT_CONNECT_TIMEOUT:25000}}
        readTimeout: ${REST_CLIENT_READ_TIMEOUT:${HPAN_REST_CLIENT_READ_TIMEOUT:25000}}

Il valore qui riportato è di esempio, e può essere aumentato dove sia già configurato come quanto sopra indicato.

Inoltre è possibile che il messaggio sia derivato da una risposta di eventuali apparati intermedi, dove presenti (e.s: proxy), verificare nel caso anche le configurazioni di questi ultimi.
